### ISSUE TITLE
Segmentation fault in JoinExecutor::do_merge_join_classicalgo

### ISSUE THREAD

**Issue by mmarx** [karmaresearch/vlog#10]
The following program causes a segmentation fault in `JoinExecutor::do_merge_join_classicalgo`:

```
(gdb) r
Starting program: /home/mmarx/.local/bin/vlog mat --edb edb.conf --rules rules --storemat_path out --storemat_format csv --decompressmat 1 --restrictedChase 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Parsing EDB configuration edb.conf
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Read program from file rules
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  The program might not terminate due to existential rules ...
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Starting full materialization
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=23. RulesWithDerivation=6 out of 12 Derivations so far 18
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 23: Total # derivations: 18
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=32. RulesWithDerivation=2 out of 3 Derivations so far 27
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 32: Total # derivations: 27
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=48. RulesWithDerivation=4 out of 12 Derivations so far 34
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 48: Total # derivations: 34
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=64. RulesWithDerivation=3 out of 12 Derivations so far 42
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 64: Total # derivations: 42
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=74. RulesWithDerivation=1 out of 3 Derivations so far 48
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 74: Total # derivations: 48
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=88. RulesWithDerivation=3 out of 12 Derivations so far 61
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 88: Total # derivations: 61
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=100. RulesWithDerivation=1 out of 12 Derivations so far 67
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 100: Total # derivations: 67
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=109. RulesWithDerivation=2 out of 3 Derivations so far 97
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 109: Total # derivations: 97
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  Finish pass over the rules. Step=126. RulesWithDerivation=6 out of 12 Derivations so far 159
[0xa9951bd9ccfd57f5 2018-09-06 17:28:51] INFO  After step 126: Total # derivations: 159
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] INFO  Finish pass over the rules. Step=151. RulesWithDerivation=3 out of 12 Derivations so far 249
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] INFO  After step 151: Total # derivations: 249
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] INFO  Finish pass over the rules. Step=161. RulesWithDerivation=2 out of 3 Derivations so far 285
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] INFO  After step 161: Total # derivations: 285
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] INFO  Finish pass over the rules. Step=180. RulesWithDerivation=7 out of 12 Derivations so far 487
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] INFO  After step 180: Total # derivations: 487
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] WARN  This method should be called only if we handle multiple heads properly...
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] WARN  This method should be called only if we handle multiple heads properly...
[0xa9951bd9ccfd57f5 2018-09-06 17:28:52] WARN  This method should be called only if we handle multiple heads properly...

Program received signal SIGSEGV, Segmentation fault.
std::__invoke_impl<bool, MITISorter const&, unsigned char&, unsigned char&> (__f=..., __args#0=<error reading variable>, __args#1=@0x555555790f90: 13 '\r')
    at /usr/include/c++/8/bits/invoke.h:60
60          { return std::forward<_Fn>(__f)(std::forward<_Args>(__args)...); }
(gdb) bt
#0  std::__invoke_impl<bool, MITISorter const&, unsigned char&, unsigned char&> (__f=..., __args#0=<error reading variable>, __args#1=@0x555555790f90: 13 '\r')
    at /usr/include/c++/8/bits/invoke.h:60
#1  0x00007ffff7e1d7c0 in std::__invoke<MITISorter const&, unsigned char&, unsigned char&> (__fn=..., __args#0=<error reading variable>, __args#1=@0x555555790f90: 13 '\r')
    at /usr/include/c++/8/bits/invoke.h:95
#2  0x00007ffff7e1d053 in std::reference_wrapper<MITISorter const>::operator()<unsigned char&, unsigned char&> (this=0x7fffffe79080, __args#0=<error reading variable>,
    __args#1=@0x555555790f90: 13 '\r') at /usr/include/c++/8/bits/refwrap.h:319
#3  0x00007ffff7e1c412 in __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<MITISorter const> >::operator()<__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsi
gned char, std::allocator<unsigned char> > > > (this=0x7fffffe79080,
    __it1=<error reading variable: Cannot access memory at address 0x5555557a2000>, __it2=13 '\r') at /usr/include/c++/8/bits/predefined_ops.h:143
#4  0x00007ffff7e1c304 in std::__unguarded_partition<__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<MITISorter const> > > (__first=<error reading variable: Cannot acc
ess memory at address 0x5555557a2000>, __last=0 '\000',
    __pivot=13 '\r', __comp=...) at /usr/include/c++/8/bits/stl_algo.h:1902
#5  0x00007ffff7e1b13e in std::__unguarded_partition_pivot<__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<MITISorter const> > > (__first=13 '\r', __last=0 '\000', __c
omp=...) at /usr/include/c++/8/bits/stl_algo.h:1923
#6  0x00007ffff7e1999b in std::__introsort_loop<__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, long, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<MITISorter const> > > (__first=13 '\r', __last=0 '\000', __depth_
limit=7, __comp=...) at /usr/include/c++/8/bits/stl_algo.h:1953
#7  0x00007ffff7e17d15 in std::__sort<__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, __gnu_cxx::__ops::_Iter_comp_iter<std::reference_wrapper<MITISorter const> > > (__first=13 '\r', __last=0 '\000', __comp=...) at /usr/incl
ude/c++/8/bits/stl_algo.h:1968
#8  0x00007ffff7e167a6 in std::sort<__gnu_cxx::__normal_iterator<unsigned char*, std::vector<unsigned char, std::allocator<unsigned char> > >, std::reference_wrapper<MITISorter const> > (__first=13 '\r', __last=0 '\000', __comp=...) at /usr/include/c++/8/bits/stl_algo.h:4866
#9  0x00007ffff7e12d07 in MergerInternalTableItr::MergerInternalTableItr (this=0x7fffffe79250, iterators=std::vector of length 26, capacity 32 = {...},
    positionsToSort=std::vector of length 0, capacity 0, nfields=2 '\002') at /home/mmarx/proj/c++/vlog/src/vlog/forward/fcinttable.cpp:906
#10 0x00007ffff7e300fe in FilterHashJoin::run (this=0x7fffffe797f0, inputTables=std::vector of length 26, capacity 32 = {...}, cartprod=true, startCarprod=0, endCartprod=2,
    ps=std::vector of length 0, capacity 0, processedTables=@0x7fffffe7aa6c: 29, valueColumnsToFilter=0x0, columnsToFilterOut=0x0)
    at /home/mmarx/proj/c++/vlog/src/vlog/forward/filterhashjoin.cpp:293
#11 0x00007ffff7e434f4 in JoinExecutor::execSelectiveHashJoin (currentRule=..., naiver=0x7ffff69ac010, map=..., doublemap=..., resultsContainer=0x555555763430,
    njoinfields=1 '\001', idxJoinField1=1 '\001', idxJoinField2=0 '\000', outputLiterals=0x0, literal=..., rowSize=2 '\002', posToSort=std::vector of length 0, capacity 0,
    values=std::vector of length 2, capacity 2 = {...}, literalSharesVarsWithHead=false, min=179, max=18446744073709551615, filterValueVars=0x0,
    processedTables=@0x7fffffe7aa6c: 29) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:839
#12 0x00007ffff7e4454a in JoinExecutor::hashjoin (t1=0x55555578cbc0, naiver=0x7ffff69ac010, outputLiterals=0x0, literal=..., min=179, max=18446744073709551615,
    filterValueVars=0x0, joinsCoordinates=std::vector of length 1, capacity 1 = {...}, output=0x555555763430, lastLiteral=0, ruleDetails=..., hv=...,
    processedTables=@0x7fffffe7aa6c: 29, nthreads=-1) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:1040
#13 0x00007ffff7e41e80 in JoinExecutor::join (naiver=0x7ffff69ac010, t1=0x55555578cbc0, outputLiterals=0x0, literal=..., min=179, max=18446744073709551615,
    filterValueVars=0x0, joinsCoordinates=std::vector of length 1, capacity 1 = {...}, output=0x555555763430, lastLiteral=false, ruleDetails=..., hv=...,
    processedTables=@0x7fffffe7aa6c: 29, currentLiteral=2, nthreads=-1) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:569
#14 0x00007ffff7e95c5f in SemiNaiver::executeRule (this=0x7ffff69ac010, ruleDetails=..., heads=std::vector of length 1, capacity 1 = {...}, iteration=228,
    finalResultContainer=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:1099
#15 0x00007ffff7e94e45 in SemiNaiver::executeRule (this=0x7ffff69ac010, ruleDetails=..., iteration=228, finalResultContainer=0x0)
    at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:919
#16 0x00007ffff7e916e8 in SemiNaiver::executeUntilSaturation (this=0x7ffff69ac010, ruleset=std::vector of length 12, capacity 16 = {...},
    costRules=std::vector of length 221, capacity 256 = {...}, fixpoint=true, timeout=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:372
#17 0x00007ffff7e90432 in SemiNaiver::executeRules (this=0x7ffff69ac010, edbRuleset=std::vector of length 0, capacity 0, ruleset=std::vector of length 12, capacity 16 = {...},
    costRules=std::vector of length 221, capacity 256 = {...}, fixpoint=true, timeout=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:220
#18 0x00007ffff7e90ffb in SemiNaiver::run (this=0x7ffff69ac010, lastExecution=0, it=1, timeout=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:317
#19 0x00005555555c2283 in SemiNaiver::run (this=0x7ffff69ac010, timeout=0x0) at /home/mmarx/proj/c++/vlog/include/vlog/seminaiver.h:155
#20 0x00005555555b95e2 in launchFullMat (argc=14, argv=0x7fffffffdbb8, pathExec="/home/mmarx/proj/vlog/segfault", db=..., vm=..., pathRules="rules")
    at /home/mmarx/proj/c++/vlog/src/launcher/main.cpp:727
#21 0x00005555555bdf1f in main (argc=14, argv=0x7fffffffdbb8) at /home/mmarx/proj/c++/vlog/src/launcher/main.cpp:1089
```

```
first(X) :- frst(X)
last(X) :- lst(X)
start(X) :- strt(X)
stop(X) :- stp(X)
next(X,Y) :- nxt(X,Y)

notLast(X) :- next(X,Y),last(Y)
notLast(X) :- next(X,Y),notLast(Y)
cont(X) :- next(X,Y),stop(Y)
cont(X) :- next(X,Y),cont(Y)

level(X,L) :- frst(X),strt(L)
level(Y,L) :- next(X,Y),level(X,L)

stage(X,L,S) :- level(X,L),frst(S)
stage(Y,L,S) :- next(X,Y),stage(X,L,S)
stage(Y,L,T) :- succ0(X,Y),stage(X,L,S),next(S,T)

succ0(X,Y) :- stage(X,L,S),nxt(S,T),notLast(T)

first(Y) :- succ0(X,Y),first(X)
succ1(X,Z),next(Y,Z) :- succ0(X,Y)
next(X,Y) :- next(U,V),succ1(U,X),succ0(V,Y)
last(Y) :- last(X),succ1(X,Y)

succ0(X,Y) :- stage(X,L,S),next(L,M),next(S,T),last(T),cont(M)
level(Y,M) :- succ0(X,Y),stage(X,L,S),next(L,M),next(S,T),last(T),cont(M)
```

edb.conf:
```
EDB0_predname=frst
EDB0_type=INMEMORY
EDB0_param0=.
EDB0_param1=first
EDB1_predname=lst
EDB1_type=INMEMORY
EDB1_param0=.
EDB1_param1=last
EDB2_predname=strt
EDB2_type=INMEMORY
EDB2_param0=.
EDB2_param1=start
EDB3_predname=stp
EDB3_type=INMEMORY
EDB3_param0=.
EDB3_param1=stop
EDB4_predname=nxt
EDB4_type=INMEMORY
EDB4_param0=.
EDB4_param1=next
```

first.csv
```
c1
```

last.csv:
```
c3
```

start.csv:
```
d1
```

stop.csv:
```
d3
```

next.csv:
```
c1,c2
c2,c3
d1,d2
d2,d3
```

**Comment by mmarx** [comment]
I agree, the segfault is gone now. Thanks for all the fixes!
