### ISSUE TITLE
Assertion `o->getNCopyFromFirst() == 1' failed.

### ISSUE THREAD

**Issue by mmarx** [karmaresearch/vlog#3]
Hi,

I'm hitting an assertion failure in `JoinExecutor::hashjoin`:
```
(gdb) run
Starting program: /home/mmarx/.local/bin/vlog mat --edb edb.conf --rules rules --storemat_path out --storemat_format csv --decompressmat 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[0xa9951bd9ccfd57f5 2018-08-17 16:02:47] INFO  Parsing EDB configuration edb.conf
[0xa9951bd9ccfd57f5 2018-08-17 16:02:47] INFO  Read program from file rules
[0xa9951bd9ccfd57f5 2018-08-17 16:02:47] INFO  The program might not terminate due to existential rules ...
[0xa9951bd9ccfd57f5 2018-08-17 16:02:47] INFO  Starting full materialization
[0xa9951bd9ccfd57f5 2018-08-17 16:02:47] INFO  Finish pass over the rules. Step=11. RulesWithDerivation=3 out of 3 Derivations so far 24
[0xa9951bd9ccfd57f5 2018-08-17 16:02:47] INFO  After step 11: Total # derivations: 24
vlog: /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:951: static void JoinExecutor::hashjoin(const FCInternalTable*, SemiNaiver*, const std::vector<Literal>*, const Literal&, size_t, size_t, const std::vector<std::pair<unsigned char, unsigned char> >*, std::vector<std::pair<unsigned char, unsigned char> >, ResultJoinProcessor*, int, const RuleExecutionDetails&, const RuleExecutionPlan&, int&, int): Assertion `o->getNCopyFromFirst() == 1' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6a6bf3b in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6a6bf3b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6a6d2f1 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff6a64a8a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff6a64b02 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff7e43b7c in JoinExecutor::hashjoin (t1=0x555555656480, naiver=0x7ffff69ac010, outputLiterals=0x7fffffe7af50, literal=..., min=7, max=18446744073709551615, filterValueVars=0x0, joinsCoordinates=std::vector of length 1, capacity 1 = {...}, output=0x555555645290, 
    lastLiteral=1, ruleDetails=..., hv=..., processedTables=@0x7fffffe7aa8c: 5, nthreads=-1) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:951
#5  0x00007ffff7e41cfe in JoinExecutor::join (naiver=0x7ffff69ac010, t1=0x555555656480, outputLiterals=0x7fffffe7af50, literal=..., min=7, max=18446744073709551615, filterValueVars=0x0, joinsCoordinates=std::vector of length 1, capacity 1 = {...}, output=0x555555645290, 
    lastLiteral=true, ruleDetails=..., hv=..., processedTables=@0x7fffffe7aa8c: 5, currentLiteral=1, nthreads=-1) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:569
#6  0x00007ffff7e95a51 in SemiNaiver::executeRule (this=0x7ffff69ac010, ruleDetails=..., heads=std::vector of length 3, capacity 3 = {...}, iteration=12, finalResultContainer=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:1099
#7  0x00007ffff7e94c37 in SemiNaiver::executeRule (this=0x7ffff69ac010, ruleDetails=..., iteration=12, finalResultContainer=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:919
#8  0x00007ffff7e914da in SemiNaiver::executeUntilSaturation (this=0x7ffff69ac010, ruleset=std::vector of length 3, capacity 4 = {...}, costRules=std::vector of length 8, capacity 8 = {...}, fixpoint=false, timeout=0x0)
    at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:372
#9  0x00007ffff7e90224 in SemiNaiver::executeRules (this=0x7ffff69ac010, edbRuleset=std::vector of length 0, capacity 0, ruleset=std::vector of length 3, capacity 4 = {...}, costRules=std::vector of length 8, capacity 8 = {...}, fixpoint=false, timeout=0x0)
    at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:220
#10 0x00007ffff7e90e63 in SemiNaiver::run (this=0x7ffff69ac010, lastExecution=0, it=1, timeout=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:322
#11 0x00005555555c2283 in SemiNaiver::run (this=0x7ffff69ac010, timeout=0x0) at /home/mmarx/proj/c++/vlog/include/vlog/seminaiver.h:155
#12 0x00005555555b95e2 in launchFullMat (argc=12, argv=0x7fffffffdbd8, pathExec="/home/mmarx/proj/vlog/tower-buggy", db=..., vm=..., pathRules="rules") at /home/mmarx/proj/c++/vlog/src/launcher/main.cpp:727
#13 0x00005555555bdf1f in main (argc=12, argv=0x7fffffffdbd8) at /home/mmarx/proj/c++/vlog/src/launcher/main.cpp:1089
(gdb) 
```

for the following ruleset and EDBs:
`edb.conf`:
```
EDB0_predname=frst
EDB0_type=INMEMORY
EDB0_param0=.
EDB0_param1=first
EDB1_predname=nxt
EDB1_type=INMEMORY
EDB1_param0=.
EDB1_param1=next
```

first.csv:
```
c1
```

next.csv:
```
c1,c2
c2,c3
d1,d2
d2,d3
```

rules:
```
first(X) :- frst(X)
next(X,Y) :- nxt(X,Y)

level(X,L) :- frst(X),frst(L)
succ0(X,Y),stage(Y,L,T),first(Y) :- first(X),level(X,L),frst(S),next(S,T)
succ1(X,Z),stage(Z,L,T),next(Y,Z) :- succ0(X,Y),stage(Y,L,T)
succ0(Y,V),next(U,V),succ1(Y,W),next(V,W),stage(V,L,T),stage(W,L,T) :- next(X,Y),succ1(X,U),stage(U,L,T)
```

This is on 3cfee5855dac0f0cd07c8f9553d52b05fbb8acc8, compiled in debug mode.

Let me know if you need further information.

**Comment by CerielJacobs** [comment]
Fixed, I think, in https://github.com/karmaresearch/vlog/commit/471e2b5bc7c2408702353da3a4bbe9582a415a29
