### ISSUE TITLE
Assertion `currentValue == valBlocks[idxBlock]' failed.

### ISSUE THREAD

**Issue by mmarx** [karmaresearch/vlog#9]
The following program fails an assertion in `JoinExecutor::do_merge_join_classicalgo`:

```
(gdb) r
Starting program: /home/mmarx/.local/bin/vlog mat --edb edb.conf --rules rules --storemat_path out --storemat_format csv --decompressmat 1 --restrictedChase 1
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Parsing EDB configuration edb.conf
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Read program from file rules
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  The program might not terminate due to existential rules ...
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Starting full materialization
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Finish pass over the rules. Step=12. RulesWithDerivation=4 out of 6 Derivations so far 10
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  After step 12: Total # derivations: 10
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Finish pass over the rules. Step=19. RulesWithDerivation=2 out of 3 Derivations so far 19
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  After step 19: Total # derivations: 19
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Finish pass over the rules. Step=27. RulesWithDerivation=2 out of 6 Derivations so far 24
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  After step 27: Total # derivations: 24
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Finish pass over the rules. Step=34. RulesWithDerivation=1 out of 6 Derivations so far 27
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  After step 34: Total # derivations: 27
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Finish pass over the rules. Step=41. RulesWithDerivation=2 out of 3 Derivations so far 51
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  After step 41: Total # derivations: 51
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Finish pass over the rules. Step=50. RulesWithDerivation=4 out of 6 Derivations so far 74
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  After step 50: Total # derivations: 74
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Finish pass over the rules. Step=57. RulesWithDerivation=1 out of 6 Derivations so far 80
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  After step 57: Total # derivations: 80
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  Finish pass over the rules. Step=64. RulesWithDerivation=2 out of 3 Derivations so far 116
[0xa9951bd9ccfd57f5 2018-09-06 17:14:24] INFO  After step 64: Total # derivations: 116
[0xa9951bd9ccfd57f5 2018-09-06 17:14:25] INFO  Finish pass over the rules. Step=73. RulesWithDerivation=3 out of 6 Derivations so far 189
[0xa9951bd9ccfd57f5 2018-09-06 17:14:25] INFO  After step 73: Total # derivations: 189
[0xa9951bd9ccfd57f5 2018-09-06 17:14:25] INFO  Finish pass over the rules. Step=90. RulesWithDerivation=3 out of 6 Derivations so far 516
[0xa9951bd9ccfd57f5 2018-09-06 17:14:25] INFO  After step 90: Total # derivations: 516
vlog: /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:1629: static void JoinExecutor::do_merge_join_classicalgo(const std::vector<const std::vector<long unsigned int>*>&, size_t, size_t, const std::vector<const std::vector<long unsigned int>*>&, size_t, size_t, const st
d::vector<unsigned char>&, const std::vector<unsigned char>&, uint8_t, const Term_t*, Output*): Assertion `currentValue == valBlocks[idxBlock]' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6a6bf3b in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt
#0  0x00007ffff6a6bf3b in raise () from /lib/x86_64-linux-gnu/libc.so.6
#1  0x00007ffff6a6d2f1 in abort () from /lib/x86_64-linux-gnu/libc.so.6
#2  0x00007ffff6a64a8a in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#3  0x00007ffff6a64b02 in __assert_fail () from /lib/x86_64-linux-gnu/libc.so.6
#4  0x00007ffff7e474e1 in JoinExecutor::do_merge_join_classicalgo (vectors1=std::vector of length 3, capacity 3 = {...}, l1=0, u1=27,
    vectors2=std::vector of length 1, capacity 1 = {...}, l2=0, u2=1, fields1=std::vector of length 0, capacity 0, fields2=std::vector of length 0, capacity 0,
    posBlocks=0 '\000', valBlocks=0x5555556b93d0, output=0x555555699570) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:1629
#5  0x00007ffff7e48d90 in JoinExecutor::do_mergejoin (filteredT1=0x5555556b5fa0, fieldsToSortInMap=std::vector of length 1, capacity 1 = {...},
    tables2=std::vector of length 1, capacity 1 = {...}, fields1=std::vector of length 0, capacity 0, posOtherVars=0x5555556ad9a0 "", valuesOtherVars=0x5555556b0f20,
    fields2=std::vector of length 0, capacity 0, output=0x5555556b1900, nthreads=-1) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:1989
#6  0x00007ffff7e45907 in JoinExecutor::mergejoin (t1=0x5555556b5ce0, naiver=0x7ffff69ac010, outputLiterals=0x7fffffe7af10, literalToQuery=..., min=0, max=4294967295,
    joinsCoordinates=std::vector of length 1, capacity 1 = {...}, output=0x5555556b1900, nthreads=-1) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:1278
#7  0x00007ffff7e41f72 in JoinExecutor::join (naiver=0x7ffff69ac010, t1=0x5555556b5ce0, outputLiterals=0x7fffffe7af10, literal=..., min=0, max=18446744073709551615,
    filterValueVars=0x0, joinsCoordinates=std::vector of length 1, capacity 1 = {...}, output=0x5555556b1900, lastLiteral=true, ruleDetails=..., hv=...,
    processedTables=@0x7fffffe7aa4c: 3, currentLiteral=2, nthreads=-1) at /home/mmarx/proj/c++/vlog/src/vlog/forward/joinprocessor.cpp:577
#8  0x00007ffff7e95c5f in SemiNaiver::executeRule (this=0x7ffff69ac010, ruleDetails=..., heads=std::vector of length 1, capacity 1 = {...}, iteration=105,
    finalResultContainer=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:1099
#9  0x00007ffff7e94e45 in SemiNaiver::executeRule (this=0x7ffff69ac010, ruleDetails=..., iteration=105, finalResultContainer=0x0)
    at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:919
#10 0x00007ffff7e916e8 in SemiNaiver::executeUntilSaturation (this=0x7ffff69ac010, ruleset=std::vector of length 6, capacity 8 = {...},
    costRules=std::vector of length 102, capacity 128 = {...}, fixpoint=true, timeout=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:372
#11 0x00007ffff7e90432 in SemiNaiver::executeRules (this=0x7ffff69ac010, edbRuleset=std::vector of length 0, capacity 0, ruleset=std::vector of length 6, capacity 8 = {...},
    costRules=std::vector of length 102, capacity 128 = {...}, fixpoint=true, timeout=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:220
#12 0x00007ffff7e90ffb in SemiNaiver::run (this=0x7ffff69ac010, lastExecution=0, it=1, timeout=0x0) at /home/mmarx/proj/c++/vlog/src/vlog/forward/seminaiver.cpp:317
#13 0x00005555555c2283 in SemiNaiver::run (this=0x7ffff69ac010, timeout=0x0) at /home/mmarx/proj/c++/vlog/include/vlog/seminaiver.h:155
#14 0x00005555555b95e2 in launchFullMat (argc=14, argv=0x7fffffffdb98, pathExec="/home/mmarx/proj/vlog/joinprocessor-assertion", db=..., vm=..., pathRules="rules")
    at /home/mmarx/proj/c++/vlog/src/launcher/main.cpp:727
#15 0x00005555555bdf1f in main (argc=14, argv=0x7fffffffdb98) at /home/mmarx/proj/c++/vlog/src/launcher/main.cpp:1089
(gdb)
```

```
next(X,Y) :- nxt(X,Y)

notLast(X) :- next(X,Y),last(Y)
notLast(X) :- next(X,Y),notLast(Y)

level(X,L) :- first(X),first(L)

stage(X,L,S) :- level(X,L),first(S)
stage(Y,L,S) :- next(X,Y),stage(X,L,S)
stage(Y,L,T) :- succ0(X,Y),stage(X,L,S),next(S,T)

succ0(X,Y) :- stage(X,L,S),nxt(S,T),notLast(T)
succ0(X,Y),level(Y,M) :- stage(X,L,S),nxt(L,M),nxt(S,T),last(T)

succ1(X,Z),next(Y,Z) :- succ0(X,Y)
next(X,Y) :- next(U,V),succ1(U,X),succ0(V,Y)
```

edb.conf:
```
EDB0_predname=first
EDB0_type=INMEMORY
EDB0_param0=.
EDB0_param1=first
EDB1_predname=last
EDB1_type=INMEMORY
EDB1_param0=.
EDB1_param1=last
EDB2_predname=nxt
EDB2_type=INMEMORY
EDB2_param0=.
EDB2_param1=next
```

first.csv
```
c1
```

last.csv:
```
c3
```

next.csv:
```
c1,c2
c2,c3
d1,d2
d2,d3
```

**Comment by CerielJacobs** [comment]
Should VLog terminate with this input? I did fix some things, but now this example seems to run forever.

**Comment by mmarx** [comment]
I stumbled upon this program while trying to minimise another program. In the process, I removed some of the EDB predicates, and while materialisation of the program should still terminate, it will now introduce roughly 10⁷⁸ new values … So I'd say this works as expected.
